title: <p align="center"> Nithiesh Kumar M </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/nithieshkumarm/">LinkedIn</a> |
  <a href="https://github.com/nithieshmurugan">GitHub</a>
  
  <br>   
  I'm working on Data processing, Big Data, Machine learning & NLP related problems.
  Also handing the Big Data from real-time Ad call data.
  Working with Industry leading Enterprise Data processing Engine team.
  Working in Data processing domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal